#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#
# 基本信息
name: 轩轩
description: 这是一个整理记录的博客
avatar: https://raw.githubusercontent.com/dyx2019/dyx2019.github.io/master/images/avatar.jpg
# favicon（出现在浏览器tab上）图片URL
favicon: https://raw.githubusercontent.com/dyx2019/dyx2019.github.io/master/images/avatar.jpg


# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 目录
    url: /archive
  - name: 文章
    url: /tags
  - name: 关于
  url: /about

# 每页的文章数
paginate: 8

# 社交网络链接，它们会作为图标出现在你的网站页脚中
footer-links: 
  weibo: # frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  email: dyx2201@163.com 
  github: # FromEndWorld/loffer #https://github.com/<>

# 站点页脚的文字
footer-text: Copyright (c) 2019 来自过去

# 输入Disqus shortname，即可添加评论区
disqus: loffer #shortname

# 输入Google Analytics web tracking code
google_analytics:

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /dyx2019.github.io


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

excerpt_separator: ---
